import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  metadataBase: new URL("https://www.recipebuilder.co"),
  title:
    "RecipeBuilder — Food Labeling & Recipe Management Software",
  description:
    "RecipeBuilder auto-generates FDA, EU, and GCC/SFDA-compliant nutrition labels, barcodes, and QR codes from your recipes using 20,000+ USDA ingredients. 40+ languages. From $29/mo (annual).",
  keywords: [
    "recipe management software",
    "food labeling software",
    "nutrition label generator",
    "FDA food labeling",
    "EU food compliance",
    "food label maker",
    "recipe cost analysis",
    "food barcode generator",
    "nutrition facts generator",
    "multi-language food labels",
    "USDA database",
    "food business software",
    "recipe inventory management",
    "food packaging artwork",
    "QR code nutrition label",
    "recipe nutrition calculator",
    "food manufacturer software",
    "restaurant recipe management",
    "bakery labeling software",
    "meal plan nutrition software",
    "food label compliance",
    "nutrition facts panel",
    "allergen labeling",
    "food safety compliance",
  ],
  authors: [{ name: "ByteBeam" }],
  creator: "ByteBeam",
  publisher: "ByteBeam",
  openGraph: {
    title:
      "RecipeBuilder — Food Labeling & Recipe Management for Food Businesses",
    description:
      "Auto-generate FDA, EU, and GCC/SFDA-compliant nutrition labels, barcodes, and QR codes from recipes. 20,000+ USDA ingredients. From $29/mo (annual).",
    url: "https://www.recipebuilder.co",
    siteName: "RecipeBuilder",
    type: "website",
    locale: "en_US",
    // OG image is auto-generated by app/opengraph-image.tsx convention
  },
  twitter: {
    card: "summary_large_image",
    title: "RecipeBuilder — Food Labeling & Recipe Management",
    description:
      "Auto-generate FDA, EU, and GCC/SFDA-compliant nutrition labels, barcodes, and QR codes from recipes. From $29/mo (annual).",
    // Twitter image inherits from opengraph-image convention
  },
  robots: {
    index: true,
    follow: true,
    "max-snippet": -1,
    "max-image-preview": "large",
    "max-video-preview": -1,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  alternates: {
    canonical: "https://www.recipebuilder.co",
    types: {
      "application/rss+xml": [
        {
          url: "https://www.recipebuilder.co/feed.xml",
          title: "RecipeBuilder Blog",
        },
      ],
    },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="alternate"
          type="application/rss+xml"
          title="RecipeBuilder Blog"
          href="https://www.recipebuilder.co/feed.xml"
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "SoftwareApplication",
              name: "RecipeBuilder",
              applicationCategory: "BusinessApplication",
              operatingSystem: "Web",
              description:
                "Recipe management and food labeling platform for food businesses. Auto-generate nutrition labels, barcodes, QR codes, and packaging artwork compliant with FDA, EU, GCC, and other regulatory frameworks.",
              offers: {
                "@type": "AggregateOffer",
                priceCurrency: "USD",
                lowPrice: "29",
                highPrice: "99",
                offerCount: "3",
                category: "SaaS",
                availability: "https://schema.org/InStock",
              },
              url: "https://www.recipebuilder.co",
              creator: {
                "@type": "Organization",
                name: "ByteBeam",
                url: "https://www.bytebeam.co",
              },
              featureList: [
                "Auto-generate food labels from recipes",
                "Barcode generation for product identification",
                "QR code for nutrition facts",
                "Full USDA FoodData Central database access",
                "Multi-language labels for FDA, EU, GCC & more",
                "Recipe cost analysis and profit tracking",
                "Real-time stock and inventory tracking",
                "Auto-generated packaging artwork",
                "Traffic light nutrition labels",
                "Allergen declarations",
              ],
            }),
          }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "Organization",
              name: "ByteBeam",
              url: "https://www.bytebeam.co",
              contactPoint: {
                "@type": "ContactPoint",
                email: "info@bytebeam.co",
                contactType: "sales",
                areaServed: "Worldwide",
                availableLanguage: ["English", "Arabic"],
              },
              brand: {
                "@type": "Brand",
                name: "RecipeBuilder",
                url: "https://www.recipebuilder.co",
              },
              address: {
                "@type": "PostalAddress",
                addressLocality: "Dubai",
                addressCountry: "AE",
              },
            }),
          }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "WebSite",
              name: "RecipeBuilder",
              url: "https://www.recipebuilder.co",
              description:
                "Food labeling and recipe management platform for food businesses. Auto-generates FDA, EU, and GCC/SFDA-compliant nutrition labels using 20,000+ USDA-verified ingredients.",
              publisher: {
                "@type": "Organization",
                name: "ByteBeam",
                url: "https://www.bytebeam.co",
              },
              potentialAction: {
                "@type": "SearchAction",
                target: {
                  "@type": "EntryPoint",
                  urlTemplate:
                    "https://www.recipebuilder.co/blog?q={search_term_string}",
                },
                "query-input": "required name=search_term_string",
              },
            }),
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
